services:
  postgres_users:
    image: postgres:15-alpine
    container_name: nexus_postgres
    environment:
      POSTGRES_USER: arqnexsoft
      POSTGRES_PASSWORD: arqnexsoft06
      POSTGRES_DB: NexusUsersDB
    ports:
      - "5435:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # Base de datos para Ideas y Mensajes (MongoDB)
  mongo_ideas:
    image: mongo:6.0
    container_name: nexus_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: